config/routes.rb
Rails.application.routes.draw do

  #cartes
  get 'cartes/instruments'
  post 'cartes/choice'
  get 'cartes/controles'
  get 'cartes/detenteurs'
  
  #reporting
  get 'reportings/instruments'
  get 'reportings/taxis'
  get 'reportings/agents'
  get 'reportings/ocp'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/chat',    to: 'static_pages#chat'
  
  #user controller
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  #login controller
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  
  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]
 
  resources :controles do 
    #route pour l'autocomplete d'adresse
    get :autocomplete_adress_label, :on => :collection
    resources :steps, only: [:show, :update], controller: 'controle/steps'
  end
  
  resources :detenteurs
  resources :instruments
  resources :adresses
  resources :create_controle
  
  get 'adresses/new'
  
  post 'adresses/validate'
  
  post 'adresses/search'

  post 'adresses/create'

  get 'adresses/edit'

  get 'adresses/update'
  
  get 'detenteurs/new'

  get 'detenteurs/index'

  get 'detenteurs/show'

  get 'detenteurs/edit'
  
  post 'detenteurs/validate'
  
  post 'detenteurs/search'
  
  post 'detenteurs/select_adress'
  
  get 'detenteurs/destroy'



  get 'suites/avertissement'

  get 'suites/pv'

  get 'suites/saisie'

  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
      @controles = Controle.all if logged_in?
      @controle = current_user.controles.build if logged_in?
  end
  
  def chat
      if logged_in?
        @micropost  = current_user.microposts.build
        #@feed_items = current_user.feed.paginate(page: params[:page])
        @feed_items = Micropost.paginate(page: params[:page])
      end
  end

  def help
    
  end
  
  def about
    
  end
  
  def contact
    
  end
  
  def testpage
    
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide :title, "A propos" %>
<h1>A propos</h1>
<p>
  Cette application a été conçue pour faciliter le suivi des contrôles de métrologie réalisés par les agents de l'Etat en région.
</p>

app/views/static_pages/contact.html.erb
<% provide :title, "Contact" %>
<h1> Contact page</h1>
<p>
  Loïc TOURNIER, responsable métrologie Antilles-Guyane <a mailto:"loic.tournier@loic.com">loic.tournier</a>
</p>

app/views/static_pages/help.html.erb
<% provide :title, "Aide" %>
<h1>Aide</h1>
<p>
Description des fonctions ici plus tard.
</p>

app/views/static_pages/home.html.erb
<div class="row">
<div class="col-md-12 text-light bg-primary">
  <div class ="vh-100 d-flex flex-column justify-content-center text-center">
    <h1>Bienvenue sur l'application Metro</h1>
  
    <h3>
      L'application métier des contrôles de métrologie légale.
    </h3>
  <div>
    <%= link_to "Connectez-vous", login_path, class: "btn btn-lg btn-outline-light mt-3 mr-3" %> <%= link_to "Créer un nouveau compte", signup_path, class: "btn btn-lg btn-outline-light mt-3" %>
  </div>
  </div>
</div>
</div>

app/views/static_pages/testpage.html.erb
<h1>StaticPages#test</h1>
<p>Find me in app/views/static_pages/test.html.erb</p>