config/routes.rb
Rails.application.routes.draw do

  #cartes
  get 'cartes/instruments'
  post 'cartes/choice'
  get 'cartes/controles'
  get 'cartes/detenteurs'
  
  #reporting
  get 'reportings/instruments'
  get 'reportings/taxis'
  get 'reportings/agents'
  get 'reportings/ocp'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/chat',    to: 'static_pages#chat'
  
  #user controller
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  #login controller
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  
  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]
 
  resources :controles do 
    #route pour l'autocomplete d'adresse
    get :autocomplete_adress_label, :on => :collection
    resources :steps, only: [:show, :update], controller: 'controle/steps'
  end
  
  resources :detenteurs
  resources :instruments
  resources :adresses
  resources :create_controle
  
  get 'adresses/new'
  
  post 'adresses/validate'
  
  post 'adresses/search'

  post 'adresses/create'

  get 'adresses/edit'

  get 'adresses/update'
  
  get 'detenteurs/new'

  get 'detenteurs/index'

  get 'detenteurs/show'

  get 'detenteurs/edit'
  
  post 'detenteurs/validate'
  
  post 'detenteurs/search'
  
  post 'detenteurs/select_adress'
  
  get 'detenteurs/destroy'



  get 'suites/avertissement'

  get 'suites/pv'

  get 'suites/saisie'

  
end

app/models/controle.rb
class Controle < ApplicationRecord
  belongs_to :user
  belongs_to :detenteur, optional: true

  
  #pour permettre le formulaire imbriqué d'instruments dans les contrôles
  has_many :instruments, inverse_of: :controle
  accepts_nested_attributes_for :instruments, reject_if: :all_blank, allow_destroy: true
  
  
  #validation du contrôle step by step
  validates :date, :user, presence: true,
		  if: -> { required_for_step?(:date) }
		    
  #on definit les étapes de validation
  cattr_accessor :form_steps do
  	%w(date searchdetenteur detenteur adressecontrole validationnewadresse instruments resume)
  end
  #curseur d'étape
  attr_accessor :form_step
  
  def required_for_step?(step)
  # All fields are required if no form step is present
  return true if form_step.nil?
  # All fields from previous steps are required if the
  # step parameter appears before or we are on the current step
  return true if self.form_steps.index(step.to_s) <= self.form_steps.index(form_step)
  end

end

app/controllers/controle/steps_controller.rb
class Controle::StepsController < ApplicationController
  #before_action :logged_in_user
  include Wicked::Wizard
  
  steps *Controle.form_steps
  
  def show
    @controle = Controle.find(params[:controle_id])
    case step
    when "date"
    when "searchdetenteur"
      @form = DetenteurForm.new()
    when "detenteur"
      @results = search_detenteur(session[:requete])
      if !@results
        flash[:danger] = "Aucun détenteur trouvé, recherchez un autre détenteur"
        redirect_to previous_wizard_path and return
      else
        @values = extract_data(@results)
      end
      @markers = extract_api_markers(@results)
      @form = SelectDetenteurForm.new()
    when "adressecontrole"
      @adressedetenteur = Adress.find(@controle.detenteur.adress_id)
      @markers = [{:latlng => [@adressedetenteur.lat,@adressedetenteur.long], :popup => @adressedetenteur.label}]
    when "validationnewadresse"
      res = search_adresse(params[:requete])
      if !res
        flash[:danger] = "Aucune adresse trouvée, recherchez une nouvelle adresse"
        redirect_to previous_wizard_path and return
      else
        @adresses = get_adresses_from_results(res)
        @markers = get_markers_from_results(res)
      end
    when "instruments"
    end
    render_wizard
  end
  

  def update
    @controle = Controle.find(params[:controle_id])
    case step
    when "date"
      @controle.update(valid_params(step))
    when "searchdetenteur"
      #validation du formulaire
      @form = DetenteurForm.new(params.require(:detenteur_form).permit(:requete))
      if @form.valid?
        session[:requete] = @form.requete  
      else
        render_wizard and return
      end
    when "detenteur"
      @form = SelectDetenteurForm.new(params.require(:select_detenteur_form).permit(:choix))
      if @form.valid?
        #recherche le siret sélectionné sur l'api entreprise
        et = search_siret(@form.choix)
        if Detenteur.exists?(:name => et["etablissement"]["nom_raison_sociale"])
          detenteur = Detenteur.find_by(name: et["etablissement"]["nom_raison_sociale"])
        else
          detenteur = Detenteur.create!(name: et["etablissement"]["nom_raison_sociale"], 
                          societe: et["etablissement"]["activite_principale_entreprise"],
                          siren: et["etablissement"]["siren"])
        end
        
        if !!detenteur.adress_id
          adresse = Adress.find(detenteur.adress_id)
        else
          adresse = Adress.create!(
            label:       et["etablissement"]["geo_adresse"],
            housenumber: et["etablissement"]["numero_voie"],   
            postcode:    et["etablissement"]["code_postal"],   
            citycode:    et["etablissement"]["commune"],  
            city:        et["etablissement"]["libelle_commune"],
            lat:         et["etablissement"]["latitude"], 
            long:        et["etablissement"]["longitude"], 
            context:     et["etablissement"]["libelle_region"],
            departement_id: code_postal_to_departement(et["etablissement"]["code_postal"])
            )
        end
        #et on sauvegarde les données
        @controle.detenteur = detenteur
        detenteur.adress_id = adresse.id
        detenteur.save
        adresse.save
        @controle.save
      else
        flash[:danger] = "Aucun détenteur sélectionné, recherchez à nouveau"
        redirect_to previous_wizard_path and return
      end
    when "adressecontrole"
      if !!params[:adress][:choixadressedetenteur]
        @controle.adress_id = @controle.detenteur.adress_id
        @controle.save
        jump_to(:instruments)
      else
        if !(params[:adress][:adress_id] == "")
          @controle.adress_id = params[:adress][:adress_id]
          @controle.save
          jump_to(:instruments)
        else
          skip_step(requete: params[:adress][:adress_label])
        end
      end
    when "validationnewadresse"
      adresse = create_adresse_if_new(adress_params)
      @controle.update(adress_id: adresse.id, adress_label: adresse.label)
    when "instruments"
      puts "paramètres en cours: #{valid_params(step)}"
      if @controle.update_attributes(valid_params(step))
        flash[:success] = "Controle enregistré !"
      else
        flash[:danger] = "Erreur lors de la sauvegarde du contrôle"
      end
    when "resume"
    end
    
    render_wizard @controle
  end
  
  private

  def valid_params(step)
  	permitted_attributes = case step
  	  when "date"
  	    [:date, :user_id]
  	 when "detenteur"
  	    [:date, :detenteur_id, :user_id, :categorie_id, :adress_label, :adress_id, 
  	    ]
  	  when "validationadresse"
  	    [:adress_id]

  	  when "instruments"
  	    [instruments_attributes: [:name, :detenteur_id, :categorie_id, :_destroy, 
                                  :dernierevp, :carnetmetro, :accepte, :refuse, :avertissement, :pv, :scelles, :motif,
        details: [:marque, :type, :numserie]]]
  	  end
  	params.require(:controle).permit(permitted_attributes).merge(form_step: step)
  end
  
  def adress_params
    #params.require(:adress).permit(attributes: [:housenumber, :label, :postcode, :citycode, :city, :context, :lat, :long])
    eval(params.require(:adress).permit(:attributes)[:attributes])
  end
  def controle_params
    params
    .require(:controle)
    .permit()
  end
end

class DetenteurForm
    include ActiveModel::Model
    
    attr_accessor :requete
    validates :requete, presence: {message: ": ne peut pas être vide, inscrivez le nom d'un détenteur."}
end

class SelectDetenteurForm
  include ActiveModel::Model
  attr_accessor :choix
  validates :choix, presence: {message: ": vous devez choisir un détenteur."}
end

app/controllers/controles_controller.rb
class ControlesController < ApplicationController
  before_action :logged_in_user
  #autocomplete
  autocomplete :adress, :label, :full => true
  

  def index
    respond_to do |format|
      format.html
      format.json { render json: ControleDatatable.new(params, view_context: view_context) }
    end
  end
  
  def new
    @controle = current_user.controles.build
  end
  
  def edit
    @controle = Controle.find(params[:id])
  end
  
  def update
    @controle = Controle.find(params[:id])
    add_detenteur_to_instruments
    if @controle.update_attributes(controle_params)
      flash[:success] = "Controle modifié"
      redirect_to controles_path
    else
      render 'edit'
    end
  end

  def show
    @controle = Controle.find(params[:id])
  end
  
  def create
    @controle = current_user.controles.build
    @controle.save(validate: false)
    redirect_to controle_step_path(@controle, Controle.form_steps.first)
  end

  def destroy
    @controle = Controle.find(params[:id])
    if @controle.destroy
      flash[:success] = "Contrôle supprimé"
      redirect_to controles_path
    else
      flash.now[:danger] = "Erreur lors de la suppression du contrôle"
      render 'edit'
    end
  end
  
  def controle_params
      params
      .require(:controle)
      .permit(:date, :detenteur_id, :user_id, :categorie_id, :adress_label, :adress_id, instruments_attributes: [:name, :detenteur_id, :categorie_id, :_destroy, :dernierevp, :carnetmetro, :accepte, :refuse, :avertissement, :pv, :scelles, :motif, details: [:marque, :type, :numserie]])
      #.permit(:date, :detenteur_id, :user_id, :categorie_id, :adresse, instruments_attributes: Instrument.attribute_names.map(&:to_sym).push(:_destroy)).permit!
  end
  
  def add_detenteur_to_instruments
    if !!params[:controle][:instruments_attributes]
      params[:controle][:instruments_attributes].values.each do |par|
        par[:detenteur_id] = params[:controle][:detenteur_id]
      end
    end  
  end
  
end

app/helpers/controles/steps_controller_helper.rb
module Controles::StepsControllerHelper
end

app/helpers/controles/steps_helper.rb
module Controles::StepsHelper
end

app/helpers/controles_helper.rb
module ControlesHelper

end

app/views/controles/_controle.html.erb
<tr>
  <td><%=link_to "#{controle.date}",controle_path(controle.id)%></a></td>
  <td><%= controle.detenteur.name %></td>
  <td><%= Adress.find(controle.adress_id).label if !!controle.adress_id %> </td>
  <td><%= controle.user.name %></td>
  <td><%= nombre_instruments(controle) %>
  </td>
</tr>

app/views/controles/_controle_resume.html.erb
<div class ="container-fluid form">
  <h4>Contrôle réalisé le <%= @controle.date %> par <%= @controle.user.name %> </h4>
  
  <div class = "row">
    <div class="card-body d-flex flex-column align-items-start">
  	<h4 class="card-title text-primary">Détenteur</h4>
    <p><b><%= @controle.detenteur.name %></b></p>
    <p><%= Adress.find(@controle.detenteur.adress_id).label %></p>
    </div>
    
    <div class="card-body d-flex flex-column align-items-start">
  	<h4 class="card-title text-primary">Adresse du contrôle</h4>
    <p><%= Adress.find(@controle.adress_id).label %></p>
    </div>
  </div>

  <h4>Instruments contrôlés</h4>

  
  <div class ="row ml-2 mr-2">
    <% @controle.instruments.each do |i| %>
    
    <div class="card-body  bg-white border rounded "style="width: 18rem;">
      <h5 class="card-title text-primary"><%= i.categorie.name %></h5>
       <p><b>marque : </b><%= i.details["marque"] %>, <b>type: </b> <%= i.details["type"] %>, <b>n°:</b> <%= i.details["numserie"] %></p>
       <p><b>dernière VP : </b><%= i.dernierevp %>, <b>carnet metro:</b> <%= if i.carnetmetro then "oui" else "non" end %></p>
       <p><b>Accepté : </b><%= if i.accepte then "oui" else "non" end %></p>
    </div>
    <% end %>
  </div>
  
</div>

app/views/controles/_form.html.erb
<div class ="container-fluid form">
  <h3 align="left">Renseignez les données du contrôle</h3>
    <%= simple_form_for @controle do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <div class="form-group form-inline">
      <%= f.input :date,label: "Date du contrôle ", input_html: { 'data-provide': 'datepicker', value: @controle.date }, :as => :string %> 
      &emsp; réalisé par : &ensp; <%= f.collection_select :user_id, User.all, :id, :name, {:prompt => 'Choisir un utilisateur'}, class: "form-control" %>
      </div>
  
      <div class="form-group">
      <%= f.label :detenteur, "Detenteur :  "%> <%= f.collection_select :detenteur_id, Detenteur.all, :id, :name, {:prompt => 'Choisir un détenteur'}, class: "form-control" %> 
      <%= link_to "Nouveau détenteur", new_detenteur_path %>
      </div>
      
      <%= f.hidden_field :adress_id %>
      <%= f.label :adress_label, "Adresse :" %>
      <%= f.autocomplete_field :adress_label, autocomplete_adress_label_controles_path, :id_element => '#controle_adress_id', 'data-noMatchesLabel' => "Aucune adresse trouvée", :class => "form-control"%>
      <%= link_to "Ajouter une adresse à la base de données", new_adress_path %>
      <script>
      $('#controle_adress_label').bind('railsAutocomplete.select', function(event, data){
      if (data.item.value == "Aucune adresse trouvée") {
                    location.href = "/adresses/new/?origin=new_controle_path"
                  }
      });    
      </script>

      <div id='instruments'>
      <h3>Instruments : </h3>
        <%= f.simple_fields_for :instruments do |instru| %>
          <%= render 'instrument_fields', :f => instru %>
        <% end %>
        <div class='links'>
          <%= link_to_add_association 'Ajouter', f, :instruments, class: "btn btn-success" %>
        </div>

      </div>  
       
      <br>
      <%= f.submit "#{button_name}", class: "btn btn-primary" %> <%= link_to("Supprimer",controle_path, method: :delete, data: { confirm: "Etes-vous sûr ?" }, class: "btn btn-secondary") if params[:action]=='edit'  %>
      </div>
    <% end %>
</div>

app/views/controles/_instrument_fields.html.erb
<div class='nested-fields'>
  <div class="form-group" >
    
      <div class="row">
        <%= f.collection_select :categorie_id, Categorie.all, :id, :name, {:prompt => 'Choisir une catégorie'}, class: "form-control" %>
        <%= f.simple_fields_for :details do |d| %>
      </div>
        <%= f.hidden_field :detenteur_id, input_html: {value: @controle.detenteur_id }%>
      <div class="row">
        
        <div class="col md-4">
          <div class="row">
            <div class="col"> <%= d.input :marque,label: "Marque : ", wrap_with: { tag: 'p', class: 'form-inline' } %> </div>
            <div class="col">  <%= d.input :type, label: "Type : ",item_wrapper: {tag: 'p'}, input_html: {class: 'form-inline'}, label_html: { class: 'form-inline' } %> </div>
            <div class="col"><%= d.input :numserie, label: "N° série : " %></div>

            <div class="col"><%= f.input :dernierevp, label: "Date VP : ", input_html: { 'data-provide': 'datepicker' } %></div>
          </div>
          <div class="row"><%= f.input :carnetmetro, label: "Présence carnet métrologique", as: :boolean %></div>
        </div>
        
        <div class="col md-6">
          <div bordered> <p><strong>Sanction </strong></p>
          <div class="form-inline">
          <%= f.input :accepte, label: "Accepté", as: :boolean, class: "custom-checkbox" %> 
           
          <%= f.input :avertissement, label: "Avertissement", as: :boolean %> 
          <%= f.input :pvp, label: "Avis de PV pénal", as: :boolean %> 
          <%= f.input :pva, label: "Avis de PV administratif", as: :boolean %> 
          <%= f.input :scelles, label: "Mise sous scellés", as: :boolean %>  
          </div>
          <%= f.input :motif, label: "Motif:  " %>
          <div align="right"><%= link_to_remove_association "Supprimer", f, class:"btn btn-secondary" %></div>
        </div></div>
        
      </div>
  </div>
    <% end %> 
</div>

app/views/controles/edit.html.erb
<h1>Modification du contrôle du <%= @controle.date %></h1>
<%= render 'form' %>

app/views/controles/index.html.erb
<div class="row">
  <div class="col" align="left">
    <h2 class="pt-3 pb-3">Contrôles réalisés</h2>
  </div>
  <div class="col" align="right">
    <%= link_to('Nouveau contrôle', controles_path, class:"btn btn-primary mt-3", method: :post)%>
  </div>
</div>



<table class="table table-striped" id="controles-datatable" data-source="<%= controles_path(format: :json) %>">
        <thead>
          <tr>
            <th>Date</th>
            <th>Détenteur</th>
            <th>Lieu</th>
            <th>Agent de contrôle</th>
            <th>Instruments controlés</th>
          </tr>
        </thead>
      <tbody>
      </tbody>
      
</table>

app/views/controles/new.html.erb
<h1 align="center">Ajout d'un nouveau contrôle</h1>
<%= render 'form' %>

app/views/controles/show.html.erb
<% render 'controle_resume' %>