config/routes.rb
Rails.application.routes.draw do

  #cartes
  get 'cartes/instruments'
  post 'cartes/choice'
  get 'cartes/controles'
  get 'cartes/detenteurs'
  
  #reporting
  get 'reportings/instruments'
  get 'reportings/taxis'
  get 'reportings/agents'
  get 'reportings/ocp'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/chat',    to: 'static_pages#chat'
  
  #user controller
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  #login controller
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  
  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]
 
  resources :controles do 
    #route pour l'autocomplete d'adresse
    get :autocomplete_adress_label, :on => :collection
    resources :steps, only: [:show, :update], controller: 'controle/steps'
  end
  
  resources :detenteurs
  resources :instruments
  resources :adresses
  resources :create_controle
  
  get 'adresses/new'
  
  post 'adresses/validate'
  
  post 'adresses/search'

  post 'adresses/create'

  get 'adresses/edit'

  get 'adresses/update'
  
  get 'detenteurs/new'

  get 'detenteurs/index'

  get 'detenteurs/show'

  get 'detenteurs/edit'
  
  post 'detenteurs/validate'
  
  post 'detenteurs/search'
  
  post 'detenteurs/select_adress'
  
  get 'detenteurs/destroy'



  get 'suites/avertissement'

  get 'suites/pv'

  get 'suites/saisie'

  
end

app/models/detenteur.rb
class Detenteur < ApplicationRecord
  has_many :instruments
  has_many :controles
end

app/controllers/detenteurs_controller.rb
class DetenteursController < ApplicationController
  #user must be logged-in to see detenteurs and operate
  before_action :logged_in_user
  
  def new
    @detenteur = Detenteur.new()
  end

  def validate
    @res = eval(params[:etablissement][:valeur])
    @ad = @res["adresseEtablissement"]
    params[:adress] = @res["adresseEtablissement"]
  end
  
  def create
    det = params.require(:detenteur).permit(:name, :societe, :siren)
    ad = params.require(:detenteur).permit(:housenumber, :label, :city, :citycode, :postcode)
    
    #si l'adresse n'existe pas on la crée
    if Adress.where(label:ad[:label]).exists?
      @adress = Adress.find_by(label:ad[:label])
    else
      @adress = Adress.create(ad)
    end
    # si le detenteur n'existe pas on le crée
    if Detenteur.where(name: det[:name]).exists?
      @detenteur = Detenteur.find_by(name: det[:name])
    else
      @detenteur = Detenteur.create(det)
    end
    @detenteur.update_attribute(:adress_id, @adress.id)
    redirect_to edit_adress_path(@adress)
  end

  def index
    @region = params[:region] #définir ici le paramètre de la région voulue
    respond_to do |format|
      format.html
      format.json { render json: DetenteurDatatable.new(params, region: @region ) } #affichage de la datatable avec des options 
    end
  end

  def show
    @detenteur = Detenteur.find(params[:id])
    @instruments = Instrument.where(detenteur_id:@detenteur.id)
  end
  
  def update
  end

  def edit
    @detenteur = Detenteur.find(params[:id])
    
  end

  def destroy
   @detenteur = Detenteur.find(params[:id])
    if @detenteur.instruments.exists? | @detenteur.controles.exists?
      flash[:danger] = "Le détenteur est lié à des instruments ou des contrôles"
      redirect_to detenteur_path(@detenteur)
    else
      @detenteur.destroy
      flash[:success] = "Detenteur supprimé"
      redirect_to detenteurs_url
    end
  end


end
 

app/helpers/detenteurs_helper.rb
module DetenteursHelper
  def adress_for(detenteur)
    if Adress.where(:id => detenteur.adress_id).exists?
      @adress = Adress.find(detenteur.adress_id)
    else
      return false
    end
  end
end

app/views/detenteurs/_detenteur.html.erb
<tr>
  <td><a href="/detenteurs/<%= detenteur.id %>"> <%= detenteur.name %> </a> </td>
  <td><%= detenteur.societe %></td>
  <td><%= detenteur.siren %> </td>
  <td><%= link_to(adress_for(detenteur).label, edit_adress_path(adress_for(detenteur))) if !!adress_for(detenteur) %></td>
</tr>

app/views/detenteurs/_search_form.html.erb
<%= simple_form_for :search, :url => {:action => "search"} do |f| %>
     <%= f.input :name, label: "Recherche par nom" %>
     <%= f.input :siren, label: "Recherche par n° SIRET ou SIREN" %>
     <%= f.input :requete, label: "Recherche par requête INSEE directe" %><%= link_to 'accès à la documentation INSEE ici' , 'https://api.insee.fr/catalogue/site/themes/wso2/subthemes/insee/templates/api/documentation/download.jag?tenant=carbon.super&resourceUrl=/registry/resource/_system/governance/apimgt/applicationdata/provider/insee/Sirene/V3/documentation/files/INSEE%20Documentation%20API%20Sirene%20Services-V3.7%20et%20V3.8.pdf' %>
     
    <%= f.submit "Rechercher", class: "btn btn-primary"  %>
<% end %>

app/views/detenteurs/destroy.html.erb
<h1>Detenteurs#destroy</h1>
<p>Find me in app/views/detenteurs/destroy.html.erb</p>

app/views/detenteurs/edit.html.erb
<h1>Modification du détenteur</h1>

<%= simple_form_for @detenteur do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    
     <%= f.input :name, input_html: { value: @detenteur.name } %>
     <%= f.input :societe, input_html: { value: @detenteur.societe } %>
     <%= f.input :siren, input_html: { value: @detenteur.siren } %>
     
     Adresse : <%= adress_for(@detenteur).label %> <%= link_to "Modifier l'adresse",edit_adress_path(adress_for(@detenteur)), class: "btn btn-primary" %>
     <br>
     
    <%= f.submit "Valider", class: "btn btn-primary" %>
<% end %>   


    

app/views/detenteurs/index.html.erb
<h2 class="pt-3 pb-3">Détenteurs</h2>

<table class="table table-striped" id="detenteurs-datatable" data-source="<%= detenteurs_path(format: :json) %>">
        <thead>
          <tr>
            <th>Nom</th>
            <th>Code APE</th>
            <th>Siren</th>
            <th>Adresse</th>
          </tr>
        </thead>
      <tbody>
      </tbody>
</table>

app/views/detenteurs/new.html.erb
<h1>Rechercher un nouveau détenteur dans la base SIRENE</h1>
<%= render 'search_form' %>

app/views/detenteurs/select_detenteur.html.erb
<% if !!@result %>
<h2>Résultats :</h2> <br>

  <%if !!@result["uniteLegale"] %>
    Le siren n° <%= @result["uniteLegale"]["siren"] %> a été trouvé et il a : <%= @result["uniteLegale"]["periodesUniteLegale"].length %> établissements.
  <% end%>
  
  <% if !!@result["etablissements"] | !!@result["etablissement"] %>
    <div>
    <%= simple_form_for :etablissement, :url => {:action => "validate"} do |f| %>
    <%= f.collection_radio_buttons(:valeur, @values, :last, :first, item_wrapper_tag: :div ) %>
    <%= f.submit "Valider", class: "btn btn-primary" %>
    <% end %>
    </div>
    
  <% end %>
<% end %>

app/views/detenteurs/show.html.erb
<div class="row">
  <div class="col">
  <h2>Détenteur : </h2>
  <p><strong>Nom :</strong> <%= @detenteur.name %></p>
  <p><strong>Société :</strong> <%= @detenteur.societe %></p>
  <p><strong>Siren :</strong> <%= @detenteur.siren %></p>
  
  <% if !!adress_for(@detenteur) %>
  <p><strong>Adresse :</strong> <%= adress_for(@detenteur).label %></p>
  <%= map(
    :center => { :latlng => [adress_for(@detenteur).lat, adress_for(@detenteur).long], :zoom => 18 },
    :markers => [{:latlng => [adress_for(@detenteur).lat,adress_for(@detenteur).long],}]  
    ) if !!adress_for(@detenteur).lat && !!adress_for(@detenteur).long %>
  
  <% end %>
  <%= link_to "Modifier", edit_detenteur_path %> <%= link_to "Supprimer", @detenteur, method: :delete, data: { confirm: "Etes-vous sûr ?" } %>
  </div>
  <div class="col">
    <h2>Instruments du détenteur</h2>
    <% @instruments.each do |i| %>
    <p><%= Categorie.find(i.categorie_id).name %>, dernière visite : <%= Controle.find(i.controle_id).date %></p>
    <% end %>
  </div>
</div>

app/views/detenteurs/validate.html.erb
<%= simple_form_for :detenteur, :url => {:controller => "detenteurs", :action => "create"} do |f| %>
     <%= f.input :name, input_html: { value: @res["uniteLegale"]["denominationUniteLegale"] } %>
     <%= f.input :societe, input_html: {value: @res["uniteLegale"]["categorieJuridiqueUniteLegale"] } %>
     <%= f.input :siren, input_html: { value: @res["siren"] } %>
     Adresse :
     <%= f.input :housenumber, input_html:{value: @ad["numeroVoieEtablissement"]} %>
     <%= f.input :label, input_html:{value: "#{@ad["numeroVoieEtablissement"]} #{@ad["typeVoieEtablissement"]} #{@ad["libelleVoieEtablissement"]} #{@ad["codePostalEtablissement"]} #{@ad["libelleCommuneEtablissement"]}"} %>
     <%= f.input :city, input_html:{value: @ad["libelleCommuneEtablissement"]} %>
     <%= f.input :citycode, input_html:{value: @ad["codeCommuneEtablissement"]} %>
     <%= f.input :postcode, input_html:{value: @ad["codePostalEtablissement"]} %>
     <%= f.submit "Valider", class: "btn btn-primary" %>
<% end %> 