config/routes.rb
Rails.application.routes.draw do

  #cartes
  get 'cartes/instruments'
  post 'cartes/choice'
  get 'cartes/controles'
  get 'cartes/detenteurs'
  
  #reporting
  get 'reportings/instruments'
  get 'reportings/taxis'
  get 'reportings/agents'
  get 'reportings/ocp'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/chat',    to: 'static_pages#chat'
  
  #user controller
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  #login controller
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  
  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]
 
  resources :controles do 
    #route pour l'autocomplete d'adresse
    get :autocomplete_adress_label, :on => :collection
    resources :steps, only: [:show, :update], controller: 'controle/steps'
  end
  
  resources :detenteurs
  resources :instruments
  resources :adresses
  resources :create_controle
  
  get 'adresses/new'
  
  post 'adresses/validate'
  
  post 'adresses/search'

  post 'adresses/create'

  get 'adresses/edit'

  get 'adresses/update'
  
  get 'detenteurs/new'

  get 'detenteurs/index'

  get 'detenteurs/show'

  get 'detenteurs/edit'
  
  post 'detenteurs/validate'
  
  post 'detenteurs/search'
  
  post 'detenteurs/select_adress'
  
  get 'detenteurs/destroy'



  get 'suites/avertissement'

  get 'suites/pv'

  get 'suites/saisie'

  
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  belongs_to :controle
  belongs_to :detenteur
  belongs_to :categorie
  
  serialize :details, Hash
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  #user must be logged-in to see instruments and operate
  before_action :logged_in_user
  
  def new
    @instrument = Instrument.new()
  end

  def index
    respond_to do |format|
      format.html
      format.json { render json: InstrumentDatatable.new(params, view_context: view_context) }
    end
  end

  def edit
    @instrument = Instrument.find(params[:id])
  end

  def update
    @instrument = Instrument.find(params[:id])
    if @instrument.update_attributes(instrument_params)
      flash[:success] = "Instrument modifié"
      redirect_to instruments_path
    else
      render 'edit'
    end
  end
  def destroy
    Instrument.find(params[:id]).destroy
    flash[:success] = "Instrument supprimé"
    redirect_to instruments_url
  end
  
  def instrument_params
    params.require(:instrument)
    .permit(:name, :detenteur_id, :categorie_id, :_destroy, :dernierevp, :carnetmetro, :refuse, :avertissement, :pv, :scelles, :motif,
      details:  [:marque, :type, :numserie])
  end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
  def listview(details)
    list = details.map{ |k,v| "<strong>#{k} : </strong>#{v}"}
    html = ""
    list.each do |e|
      html += e + "&emsp;"
    end
    html.html_safe
  end
end

app/views/instruments/_instrument.html.erb
<tr onclick="document.location='<%= instrument_path(instrument) %>'">
  <td><%= instrument.categorie.name %></td>
  <td><%= instrument.detenteur.name %> </td>
  <td><%= instrument.details.each do |i| "#{i[0]} : #{i[1]}" end %>
  <td><%= instrument.controle.date %></td>
  <td><%= Adress.find(instrument.controle.adress_id).label %></td>
</tr></a>

app/views/instruments/edit.html.erb
<h1>Modifier l'instrument</h1>
<div class='nested-fields'>
  <%= simple_form_for @instrument do |f| %>
  <div class="form-group" >
    
      <div class="row">
        <%= f.collection_select :categorie_id, Categorie.all, :id, :name, {:prompt => 'Choisir une catégorie'}, class: "form-control" %>
        <%= f.simple_fields_for :details do |d| %>
      </div>
      <div class="row">
        <div class="col md-4">
          <div class="row">
            <div class="col"> <%= d.input :marque,label: "Marque : ", wrap_with: { tag: 'p', class: 'form-inline' },input_html: {value: @instrument.details["marque"]} %> </div>
            <div class="col">  <%= d.input :type, label: "Type : ",item_wrapper: {tag: 'p'}, input_html: {class: 'form-inline', value: @instrument.details["type"]}, label_html: { class: 'form-inline' } %> </div>
            <div class="col"><%= d.input :numserie, label: "N° série : ",input_html: {value: @instrument.details["numserie"]} %></div>
            
            
            <div class="col"><%= f.input :dernierevp, label: "Date VP : ", input_html: { 'data-provide': 'datepicker', value: @instrument.dernierevp } %></div>
          </div>
          <div class="row"><%= f.input :carnetmetro, label: "Présence carnet métrologique", as: :boolean,input_html: { :checked => !!@instrument.carnetmetro } %></div>
        </div>
        <div class="col md-6">
          <div bordered> <p><strong>Sanction </strong></p>
          <div class="form-inline">
          <%= f.input :accepte, label: "Accepté", as: :boolean, class: "custom-checkbox", input_html: { :checked => !!@instrument.accepte } %> 
          <%= f.input :refuse, label: "Refusé", as: :boolean, class: "custom-checkbox", input_html: { :checked => !@instrument.accepte } %> 
          <%= f.input :avertissement, label: "Avertissement", as: :boolean, input_html: { :checked => !!@instrument.avertissement } %> 
          <%= f.input :pvp, label: "Avis de PV pénal", as: :boolean, input_html: { :checked => !!@instrument.pvp } %> 
          <%= f.input :pva, label: "Avis de PV administratif", as: :boolean, input_html: { :checked => !!@instrument.pva } %> 
          <%= f.input :scelles, label: "Mise sous scellés", as: :boolean , input_html: { :checked => !!@instrument.scelles }%>  
          </div>
          <%= f.input :motif, label: "Motif:  ", input_html: {value: @instrument.motif} %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col md-6" align="left">
        <%= f.submit "Modifier", class: "btn btn-primary" %>    
        </div>
        <div class="col md-6" align="right">
        <%= link_to "Supprimer",instrument_path, method: :delete, data: { confirm: "Etes-vous sûr ?" }, class:"btn btn-secondary" %></div>
        </div>
      </div>
  </div>
    <% end %> 
  <% end %>
</div>

app/views/instruments/index.html.erb
<h2>Instruments</h2>

<table class="table table-striped" id="instruments-datatable" data-source="<%= instruments_path(format: :json) %>">
        <thead>
          <tr>
            <th>Catégorie</th>
            <th>Détenteur</th>
            <th>Dernier Contrôle</th>
            <th>Adresse du dernier contrôle</th>
            <th>Détails</th>
            <th></th>
          </tr>
        </thead>
      <tbody>
      </tbody>
</table>

app/views/instruments/new.html.erb
<h1>Nouvel instrument</h1>
<div class='nested-fields'>
  <%= simple_form_for @instrument do |f| %>
  <div class="form-group" >
    
      <div class="row">
        <%= f.collection_select :categorie_id, Categorie.all, :id, :name, {:prompt => 'Choisir une catégorie'}, class: "form-control" %>
        <%= f.simple_fields_for :details do |d| %>
      </div>
      <div class="row">
        <div class="col md-4">
          <div class="row">
            <div class="col"> <%= d.input :marque,label: "Marque : ", wrap_with: { tag: 'p', class: 'form-inline' } %> </div>
            <div class="col">  <%= d.input :type, label: "Type : ",item_wrapper: {tag: 'p'}, input_html: {class: 'form-inline'}, label_html: { class: 'form-inline' } %> </div>
            <div class="col"><%= d.input :numserie, label: "N° série : " %></div>
            <div class="col"><%= d.input :dernierevp, label: "Date VP : ", input_html: { 'data-provide': 'datepicker' } %></div>
          </div>
          <div class="row"><%= d.input :carnetmetro, label: "Présence carnet métrologique", as: :boolean %></div>
        </div>
        <div class="col md-6">
          <div bordered> <p><strong>Sanction </strong></p>
          <div class="form-inline">
          <%= d.input :accepte, label: "Accepté", as: :boolean, class: "custom-checkbox" %> 
          <%= d.input :refuse, label: "Refusé", as: :boolean %> 
          <%= d.input :avertissement, label: "Avertissement", as: :boolean %> 
          <%= d.input :pv, label: "Avis de PV", as: :boolean %> 
          <%= d.input :scelles, label: "Mise sous scellés", as: :boolean %>  
          </div>
          <%= d.input :motif, label: "Motif:  " %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col md-6" align="left">
        <%= f.submit "Valider", class: "btn btn-primary" %>    
        </div>
 
      </div>
  </div>
    <% end %> 
  <% end %>
</div>

app/views/instruments/show.html.erb
<h1>Instruments#show</h1>
<p>Find me in app/views/instruments/show.html.erb</p>